=== minaazer/LiturgicalText/data/jsons/_schemas/songs.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "songs.json",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "english_title": {
        "type": "string"
      },
      "arabic_title": {
        "type": [
          "string",
          "null"
        ]
      },
      "themes": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "tbodies": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "rows": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "row-class": {
                    "type": "string"
                  },
                  "cells": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "english": {
                          "type": "string"
                        },
                        "enPhonicsSongs": {
                          "type": "string"
                        },
                        "arabic": {
                          "type": "string"
                        },
                        "enPhonics1": {
                          "type": "string"
                        }
                      },
                      "required": [],
                      "additionalProperties": true
                    }
                  }
                },
                "required": [
                  "cells",
                  "row-class"
                ],
                "additionalProperties": true
              }
            }
          },
          "required": [
            "rows"
          ],
          "additionalProperties": true
        }
      },
      "audio_file": {
        "type": "string"
      },
      "coptic_title": {
        "type": [
          "string",
          "null"
        ]
      }
    },
    "required": [
      "english_title",
      "tbodies",
      "themes"
    ],
    "additionalProperties": true
  }
}

=== minaazer/LiturgicalText/data/jsons/unctionOfTheSick.json
[
  {
    "english_title": "1st: Thanksgiving Prayer",
    "coptic_title": "",
    "arabic_title": "",
    "themes": [],
    "tbodies": [
      {
        "rows": [
          {
            "row-class": "text",
            "cells": [
              {
                "english": "<p>Can be found here:<br/> <a href=\"https://tasbeha.org/hymn_library/view/1833\">Full Service &gt; Thanksgiving Prayer</a></p>"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "english_title": "1st: Psalm 50 (51)",
    "coptic_title": "Ⲛⲁⲓ ⲛⲏⲓ Ⲫϯ ⲕⲁⲧⲁ ⲡⲉⲕⲛⲓϣϯ ⲛ̀ⲛⲁⲓ",
    "arabic_title": "",
    "themes": [],
    "tbodies": [
      {
        "rows": [
          {
            "row-class": "text",
            "cells": [
              {
                "english": "<p>Have mercy upon me, O God, According to Your lovingkindness; According to the multitude of Your tender mercies, Blot out my transgressions. Wash me thoroughly from my iniquity, And cleanse me from my sin. For I acknowledge my transgressions, And my sin is always before me.</p>"
              },
              {
                "coptic": "<p>Ⲛⲁⲓ ⲛⲏⲓ Ⲫ̀ⲛⲟⲩϯ ⲕⲁⲧⲁ ⲡⲉⲕⲛⲓϣϯ ⲛ̀ⲛⲁⲓ: ⲛⲉⲙ ⲕⲁⲧⲁ ⲡ̀ⲁ̀ϣⲁⲓ ⲛ̀ⲧⲉ ⲛⲉⲕⲙⲉⲧϣⲉⲛϩⲏⲧ ⲉⲕⲉ̀ⲥⲱⲗϫ ⲛ̀ⲧⲁⲁ̀ⲛⲟⲙⲓⲁ: ⲉⲕⲉ̀ⲣⲁϧⲧ ⲛ̀ϩⲟⲩⲟ̀ ⲉ̀ⲃⲟⲗ ϩⲁ ⲧⲁⲁ̀ⲛⲟⲙⲓⲁ: ⲟⲩⲟϩ ⲉⲕⲉ̀ⲧⲟⲩⲃⲟⲓ ⲉ̀ⲃⲟⲗ ϩⲁ ⲡⲁⲛⲟⲃⲓ. Ϫⲉ ⲧⲁⲁ̀ⲛⲟⲙⲓⲁ ⲁ̀ⲛⲟⲕ ϯⲥⲱⲟⲩⲛ ⲙ̀ⲙⲟⲥ: ⲟⲩⲟϩ ⲡⲁⲛⲟⲃⲓ ⲙ̀ⲡⲁⲙ̀ⲑⲟ ⲉ̀ⲃⲟⲗ ⲛ̀ⲥⲏⲟⲩ ⲛⲓⲃⲉⲛ.</p>"
              },
              {
                "arabic": "<p>إرْحَمنِي يَا الله كَعَظيمِ رَحْمتِكَ، ومِثْل كَثْرةِ رَأفتِكَ تَمْحُو إثْمِي، تَغْسلُنِي كَثيراً مِنْ إثْمِي، ومِنْ خَطيَّتِي تُطهّرنِي. لأنِّي عارفٌ بإثْمِي، وخَطيَّتِي أمَامِي في كلِّ حينٍ.</p>"
              }
            ]
          },
          {
            "row-class": "text",
            "cells": [
              {
                "english": "<p>Against You, You only, have I sinned, And done this evil in Your sight—That You may be found just when You speak, And blameless when You judge. Behold, I was brought forth in iniquity, And in sin my mother conceived me. Behold, You desire truth in the inward parts, And in the hidden part You will make me to know wisdom.</p>"
              },
              {
                "coptic": "<p>Ⲛ̀ⲑⲟⲕ ⲙ̀ⲙⲁⲩⲁⲧⲕ ⲁⲓⲉⲣⲛⲟⲃⲓ ⲉ̀ⲣⲟⲕ: ⲟⲩⲟϩ ⲡⲓⲡⲉⲧϩⲱⲟⲩ ⲁⲓⲁⲓϥ ⲙ̀ⲡⲉⲕⲙ̀ⲑⲟ ⲉ̀ⲃⲟⲗ. Ϩⲟⲡⲱⲥ ⲛ̀ⲧⲉⲕⲙⲁⲓ ϧⲉⲛ ⲛⲉⲕⲥⲁϫⲓ: ⲟⲩⲟϩ ⲛ̀ⲧⲉⲕϭⲣⲟ ⲉⲕⲛⲁϭⲓϩⲁⲡ. Ϩⲏⲡⲡⲉ ⲅⲁⲣ ϧⲉⲛ ϩⲁⲛⲁ̀ⲛⲟⲙⲓⲁ ⲁⲩⲉⲣⲃⲟⲕⲓ ⲙ̀ⲙⲟⲓ: ⲟⲩⲟϩ ϧⲉⲛ ϩⲁⲛⲛⲟⲃⲓ ⲁ̀ ⲧⲁⲙⲁⲩ ϭⲓϣϣⲱⲟⲩ ⲙ̀ⲙⲟⲓ. Ϩⲏⲡⲡⲉ ⲅⲁⲣ ⲁⲕⲙⲉⲛⲣⲉ ⲑ̀ⲙⲏⲓ: ⲛⲏⲉⲧϩⲏⲡ ⲛⲉⲙ ⲛⲏⲉ̀ⲧⲉ ⲛ̀ⲥⲉⲟⲩⲱⲛϩ ⲉ̀ⲃⲟⲗ ⲁⲛ ⲛ̀ⲧⲉ ⲧⲉⲕⲥⲟⲫⲓⲁ ⲁⲕⲧⲁⲙⲟⲓ ⲉ̀ⲣⲱⲟⲩ.</p>"
              },
              {
                "arabic": "<p>لَكَ وحْدَك أخْطأت، والشَّرُّ قدامَكَ صَنعْتُ. لِكيْ تَتَبرَّرَ في أقْوالِكَ، وتَغْلبَ مَتَى حَوكمْت. لأنِّي هَا أنَذَا بالآثَام حُبلَ بِي، وبالَخَطايَا وَلَدتْنِي أمِّي. لأنَّكَ هَكَذا قَدْ أحْبَبتُ الحقَّ، إذْ أوْضَحتَ لِي غَوامِضَ حِكْمتِكَ ومَسْتورَاتِها.</p>"
              }
            ]
          },
          {
            "row-class": "text",
            "cells": [
              {
                "english": "<p>Purge me with hyssop, and I shall be clean; Wash me, and I shall be whiter than snow. Make me hear joy and gladness, That the bones You have broken may rejoice. Hide Your face from my sins, And blot out all my iniquities.</p>"
              },
              {
                "coptic": "<p>Ⲉⲕⲉ̀ⲛⲟⲩϫϧ ⲉ̀ϫⲱⲓ ⲙ̀ⲡⲉⲕϣⲉⲛϩⲩⲥⲱⲡⲟⲛ ⲉⲓⲉ̀ⲧⲟⲩⲃⲟ: ⲉⲕⲉ̀ⲣⲁϧⲧ ⲉⲓⲉ̀ⲟⲩⲃⲁϣ ⲉ̀ϩⲟⲧⲉ ⲟⲩⲭⲓⲱⲛ. Ⲉⲕⲉ̀ⲑ̀ⲣⲓⲥⲱⲧⲉⲙ ⲉ̀ⲟⲩⲑⲉⲗⲏⲗ ⲛⲉⲙ ⲟⲩⲟⲩⲛⲟϥ ⲉⲩⲉ̀ⲑⲉⲗⲏⲗ ⲛ̀ϫⲉ ⲛⲓⲕⲁⲥ ⲉⲧⲑⲉⲃⲓⲏⲟⲩⲧ. Ⲙⲁⲧⲁⲥⲑⲟ ⲙ̀ⲡⲉⲕϩⲟ ⲥⲁⲃⲟⲗ ⲛ̀ⲛⲁⲛⲟⲃⲓ: ⲟⲩⲟϩ ⲛⲁⲁ̀ⲛⲟⲙⲓⲁ ⲧⲏⲣⲟⲩ ⲉⲕⲉ̀ⲥⲟⲗϫⲟⲩ.</p>"
              },
              {
                "arabic": "<p>تَنضَحُ عَليَّ بِزُوفَاكَ فأطَّهَّرُ، تَغْسلُنِي فَأبْيضُّ أكْثَر مِنَ الثَّلجِ. تَسْمعُنِي سُرُوراً وفَرحاً فتَبْتهجُ عِظامِي المنْسَحقةُ. إصْرِفْ وجْهَكَ عَنْ خَطايَايَ، وأمْحُ كلَّ آثَامِي.</p>"
              }
            ]
          },
          {
            "row-class": "text",
            "cells": [
              {
                "english": "<p>Create in me a clean heart, O God, And renew a steadfast spirit within me. Do not cast me away from Your presence, And do not take Your Holy Spirit from me.</p>"
              },
              {
                "coptic": "<p>Ⲟⲩϩⲏⲧ ⲉϥⲟⲩⲁⲃ ⲉⲕⲉ̀ⲥⲟⲛⲧϥ ⲛ̀ϧⲏⲧ Ⲫ̀ⲛⲟⲩϯ: ⲟⲩⲡ̀ⲛⲉⲩⲙⲁ ⲉϥⲥⲟⲩⲧⲱⲛ ⲁ̀ⲣⲓⲧϥ ⲙ̀ⲃⲉⲣⲓ ϧⲉⲛ ⲛⲏⲉⲧⲥⲁϧⲟⲩⲛ ⲙ̀ⲙⲟⲓ. Ⲙ̀ⲡⲉⲣⲃⲉⲣⲃⲱⲣⲧ ⲉ̀ⲃⲟⲗ ϩⲁ ⲡⲉⲕϩⲟ: ⲟⲩⲟϩ Ⲡⲉⲕⲡ̀ⲛⲉⲩⲙⲁ Ⲉⲑⲟⲩⲁⲃ ⲙ̀ⲡⲉⲣⲟⲗϥ ⲉ̀ⲃⲟⲗ ϩⲁⲣⲟⲓ.</p>"
              },
              {
                "arabic": "<p>قَلبِاً نَقياً أخْلقْ في يا الله، ورُوحاً مُسْتَقيماً جدِّدهُ في أحْشَائِي. لا تَطْرحْنِي مِنْ قُدَّامَ وجْهكَ، ورُوحكَ القُدُّوسِ لا تَنْزعْهُ مِنِّي.</p>"
              }
            ]
          },
          {
            "row-class": "text",
            "cells": [
              {
                "english": "<p>Restore to me the joy of Your salvation, And uphold me by Your generous Spirit. Then I will teach transgressors Your ways, And sinners shall be converted to You.</p>"
              },
              {
                "coptic": "<p>Ⲙⲟⲓ ⲛⲏⲓ ⲙ̀ⲡ̀ⲑⲉⲗⲏⲗ ⲛ̀ⲧⲉ ⲡⲉⲕⲟⲩϫⲁⲓ: ⲟⲩⲟϩ ⲛ̀ϩ̀ⲣⲏⲓ ϧⲉⲛ ⲟⲩⲡ̀ⲛⲉⲩⲙⲁ ⲛ̀ϩⲏⲅⲉⲙⲱⲛⲓⲕⲟⲛ ⲙⲁⲧⲁϫⲣⲟⲓ. Ⲉⲓⲉ̀ⲧ̀ⲥⲁⲃⲉ ⲛⲓⲁ̀ⲛⲟⲙⲟⲥ ϩⲓ ⲛⲉⲕⲙⲱⲓⲧ: ⲟⲩⲟϩ ⲛⲓⲁ̀ⲥⲉⲃⲏⲥ ⲉⲩⲉ̀ⲕⲟⲧⲟⲩ ϩⲁⲣⲟⲕ.</p>"
              },
              {
                "arabic": "<p>إمْنَحْنِي بَهْجةَ خَلاصِكَ، وبرُوح مُدبِّرٍ عَضِّدّنِي. فأُعْلِّمِ الأثَمَةَ طُرُقكَ، والمنَافِقونَ إليْكَ يَرجعونَ.</p>"
              }
            ]
          },
          {
            "row-class": "text",
            "cells": [
              {
                "english": "<p>Deliver me from the guilt of bloodshed, O God, The God of my salvation, And my tongue shall sing aloud of Your righteousness.</p>"
              },
              {
                "coptic": "<p>Ⲛⲁϩⲙⲉⲧ ⲉ̀ⲃⲟⲗ ϧⲉⲛ ϩⲁⲛⲥ̀ⲛⲱϥ Ⲫ̀ⲛⲟⲩϯ: Ⲫ̀ⲛⲟⲩϯ ⲛ̀ⲧⲉ ⲧⲁⲥⲱⲧⲏⲣⲓⲁ: ⲉϥⲉ̀ⲑⲉⲗⲏⲗ ⲛ̀ϫⲉ ⲡⲁⲗⲁⲥ ϧⲉⲛ ⲧⲉⲕⲇⲓⲕⲉⲟ̀ⲥⲩⲛⲏ.</p>"
              },
              {
                "arabic": "<p>نَجِّنِي مِنَ الدِّماء يا الله، إلَه خَلاصِي، فيَبتَّهجُ لِسانِي ببرَّكَ.</p>"
              }
            ]
          },
          {
            "row-class": "text",
            "cells": [
              {
                "english": "<p>O Lord, open my lips, And my mouth shall show forth Your praise. For You do not desire sacrifice, or else I would give it; You do not delight in burnt offering. The sacrifices of God are a broken spirit, A broken and a contrite heart—These, O God, You will not despise.</p>"
              },
              {
                "coptic": "<p>Ⲡ̀ϭⲟⲓⲥ ⲉⲕⲉ̀ⲟⲩⲱⲛ ⲛ̀ⲛⲁⲥ̀ⲫⲟⲧⲟⲩ ⲉ̀ⲣⲉ ϫⲱ ⲙ̀ⲡⲉⲕⲥ̀ⲙⲟⲩ. Ϫⲉ ⲉ̀ⲛⲉ ⲁⲕⲟⲩⲱϣ ϣⲟⲩϣⲱⲟⲩϣⲓ ⲛⲁⲓⲛⲁϯ ⲟⲛ ⲡⲉ: ϩⲁⲛϭⲗⲓⲗ ⲛ̀ϫⲟϥϫⲉϥ ⲙ̀ⲡⲉⲕϯⲙⲁϯ ⲉ̀ϩ̀ⲣⲏⲓ ⲉ̀ϫⲱⲟⲩ. Ⲡⲓϣⲟⲩϣⲱⲟⲩϣⲓ ⲛ̀ⲧⲉ Ⲫ̀ⲛⲟⲩϯ ⲟⲩⲡ̀ⲛⲉⲩⲙⲁ ⲉϥⲧⲉⲛⲛⲏⲟⲩⲧ ⲡⲉ: ⲟⲩϩⲏⲧ ⲉϥⲧⲉⲛⲛⲏⲟⲩⲧ ⲡⲉ ⲟⲩⲟϩ ⲉϥⲑⲉⲃⲓⲏⲟⲩⲧ ⲫⲁⲓ ⲛ̀ⲛⲉ Ⲫ̀ⲛⲟⲩϯ ϣⲟϣϥ.</p>"
              },
              {
                "arabic": "<p>يَا ربِّ إفْتَح شَفتَيَّ فَيُخبرُ فَمِي بَتَسْبيحِكَ. لأنَّكَ لَوْ أثَرتَ الذَّبيحةَ، لَكُنْتُ الآنَ أُعْطِي. ولَكنَّكَ لا تُسرُّ بالَمحْرقَاتِ، فالذَبيحَةُ للهِ رُوحَّ مُنْسحقَّ، القَلْبُ المنْكسِرُ والمتَواضِعُ لا يُرْذلهُ الله.</p>"
              }
            ]
          },
          {
            "row-class": "text",
            "cells": [
              {
                "english": "<p>Do good in Your good pleasure to Zion; Build the walls of Jerusalem. Then You shall be pleased with the sacrifices of righteousness, With burnt offering and whole burnt offering; Then they shall offer bulls on Your altar.</p>"
              },
              {
                "coptic": "<p>Ⲁ̀ⲣⲓⲡⲉⲑⲛⲁⲛⲉϥ Ⲡ̀ϭⲟⲓⲥ ϧⲉⲛ ⲡⲉⲕϯⲙⲁϯ ⲉ̀Ⲥⲓⲱⲛ: ⲟⲩⲟϩ ⲛⲓⲥⲟⲃⲧ ⲛ̀ⲧⲉ Ⲓⲉⲣⲟⲩⲥⲁⲗⲏⲙ ⲙⲁⲣⲟⲩⲕⲟⲧⲟⲩ. Ⲧⲟⲧⲉ ⲉⲕⲉ̀ϯⲙⲁϯ ⲉ̀ϫⲉⲛ ϩⲁⲛϣⲟⲩϣⲱⲟⲩϣⲓ ⲙ̀ⲙⲉⲑⲙⲏⲓ ⲟⲩⲁ̀ⲛⲁⲫⲟⲣⲁ ⲛⲉⲙ ϩⲁⲛϭⲗⲓⲗ. Ⲧⲟⲧⲉ ⲉⲩⲉ̀ⲓ̀ⲛⲓ ⲛ̀ϩⲁⲛⲙⲁⲥⲓ ⲉ̀ⲡ̀ϣⲱⲓ ⲉ̀ϫⲉⲛ ⲡⲉⲕⲙⲁⲛ̀ⲉⲣϣⲱⲟⲩϣⲓ.</p>"
              },
              {
                "arabic": "<p>أنْعمْ يَا ربّ بِمَسرتكَ عَلى صِهْيُون، ولْتَبنِ أسْوَارَ أورْشَلِيم. حِينَئذٍ تُسرُّ بذَبائِح البَرِّ قرباناً ومُحْرقَات. ويُقَّربون عَلى مَذابِحكَ العُجُول.</p>"
              }
            ]
          },
          {
            "row-class": "text",
            "cells": [
              {
                "english": "<p>Alleluia.</p>"
              },
              {
                "coptic": "<p>Ⲁⲗⲗⲏⲗⲟⲩⲓⲁ.</p>"
              },
              {
                "arabic": "<p>هلليلويا.</p>"
              }
            ]
          },
          {
            "row-class": "text",
            "cells": [
              {
                "english": "<p>Glory to You, O our God.</p>"
              },
              {
                "coptic": "<p>Ⲇⲟⲝⲁ ⲥⲓ ⲟ̀ Ⲑⲉⲟⲥ ⲩ̀ⲙⲱⲛ.</p>"
              },
              {
                "arabic": "<p>المجد لإلهنا.</p>"
              }
            ]
          },
          {
            "row-class": "text",
            "cells": [
              {
                "english": "<p>----<br/> Then the <a href=\"https://tasbeha.org/hymn_library/view/1846\">litany of the Sick</a> is prayed.</p>"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "english_title": "1st: The Supplications (Priest)",
    "coptic_title": "",
    "arabic_title": "",
    "themes": [],
    "tbodies": [
      {
        "rows": [
          {
            "row-class": "text",
            "cells": [
              {
                "english": "<p>The priest says these prayers and the people respond every time saying:<br/> Lord have mercy.</p>"
              },
              {
                "arabic": "<p>يقول الكاهن هذه الطلبات ويرد عليه الشعب فى كل مرة: يا رب ارحم.</p>"
              }
            ]
          },
          {
            "row-class": "text",
            "cells": [
              {
