=== minaazer/LiturgicalText/json-editor/schemas/agpeya/prime_hour.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "agpeya/prime_hour.json",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "english_title": {
        "type": "string"
      },
      "coptic_title": {
        "type": "null"
      },
      "arabic_title": {
        "anyOf": [
          {
            "type": "null"
          },
          {
            "type": "string"
          }
        ]
      },
      "title": {
        "type": "string"
      },
      "tbodies": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "rows": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "row-class": {
                    "type": "string"
                  },
                  "cells": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "english": {
                          "type": "string"
                        },
                        "arabic": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "english"
                      ],
                      "additionalProperties": true
                    }
                  }
                },
                "required": [
                  "cells",
                  "row-class"
                ],
                "additionalProperties": true
              }
            }
          },
          "required": [
            "rows"
          ],
          "additionalProperties": true
        }
      },
      "repeated_prayer_title": {
        "type": "string"
      },
      "source": {
        "type": "string"
      },
      "category": {
        "type": "string"
      }
    },
    "required": [],
    "additionalProperties": true
  }
}

=== minaazer/LiturgicalText/CRFiles/agpeya/Agpeya - Meals.json
[
  {
    "english_title": "Prayer Before Meals",
    "coptic_title": null,
    "arabic_title": "صلاة قبل الأكل",
    "title": "Prayer Before Meals",
    "tbodies": [
      {
        "rows": [
          {
            "row-class": "text",
            "cells": [
              {
                "english": "Blessed are You, O Lord who supported us from our youth and granted us Your blessings, and prepared food for every creature; for the eyes of everyone wait upon You, for You give them their food in due season. You open Your hands and fill all living things. To You is due glory, praise, blessing, and thanksgiving for the food that You have prepared for us. Stretch out Your right hand and bless this food set before us for the nourishment of our bodies. Let it be for power and health of our lives. Grant salvation, grace, blessing, and purity to all those who partake of it. Lift our minds to You at all times to seek our spiritual and eternal food. Grant that we may labor for the everlasting food that is for eternal life. Grant us to be partakers of Your evening banquet. Grant us the food of blessing, the cup of salvation, and fill our hearts with joy. Teach us, since You are the pleasure in all things, that when eating, drinking or laboring, we do it all for the glory of Your holy name. For Yours is the glory, forever and ever. Amen.",
                "arabic": "تباركت يارب يا من تعولنا منذ حداثتنا، وتهبنا خيراتك، وتهيئ الغذاء للجميع. لأن أعين الكل تترجاك، وأنت تعطيهم طعامهم في حينه. تفتح يدك فتُشبع كل حي من رضاك، لك المجد والتسبيح والبركة والشكر على كل ما أعددت لنا من الطعام. فتفضل يارب وأبسط يمينك وبارك هذا الطعام الموضوع على هذه المائدة المُعَدّة لغذاء أجسادنا. اجعله شفاء وقوة لحياتنا الجسدية، وامنح خلاصاً ونعمة وبركة وطهراً لكل المتناولين منه. ارفع عقولنا إليك كل حين لطلب طعامنا الروحي غير البائد. اعطنا أن نعمل للطعام الباقي للحياة الأبدية، وهَب لنا نصيباً في الإشتراك في وليمتك السمائية. امنحنا خبز البركة، وكأس الخلاص، واملأ قلوبنا من البهجة والفرح. انعم علينا بحياة مطمئنة هادئة، وسعادة في النفس، وصحة في الجسد. علمنا أن نطلب رضاك في كل شيء، حتى إذا أكلنا أو شربنا أو عملنا أي شيء، نعمله لمجد اسمك القدوس، لأن لك المجد إلى الأبد، آمين."
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "english_title": "Prayer After Meals",
    "coptic_title": null,
    "arabic_title": "صلاة بعد الأكل",
    "title": "Prayer After Meals",
    "tbodies": [
      {
        "rows": [
          {
            "row-class": "text",
            "cells": [
              {
                "english": "O Lord, we are not worthy of the least of all Your mercies which You have shown us today. O Lord, rich in mercies, who supports us and fills our hearts with plenty, joy and happiness, blessed be Your name. O Lord, he who eats, eats to the Lord and gives thanks to God; and he who drinks, drinks to the Lord and gives thanks to God. Therefore, if we eat or drink or do anything, we do it to the glory of God and we give Him thanks. O Lord, let us be hungry for the bread of life, for whoever eats of it never dies but lives forever. Also, let us be thirsty for the living water, for whoever drinks of it shall never thirst, but it becomes a well in him which springs up to everlasting life. We give You thanks, O Almighty God, for these and all Your blessings, through Christ Jesus our Lord. For Thine is the kingdom and the power and the glory forever and ever. Amen.",
                "arabic": "نشكرك أيها الرب الإله ضابط الكل، لأنك أنت الذي أعددت لنا هذه المائدة، التي هي دليل المحبة لنا نحن عبيدك، الذين نلنا من خيرات الأرض. نسألك يا سيدنا، ليَكثُر ما فضل عنا كبركة الخمس خبزات والسمكتين، هذه التي عُلت بها جموعاً كثيرة في البرية. صِر لنا عوناً وقوة، نحن جميع الآخذين منه، والذين صنعوا معنا رحمة، والذين خدمونا، والمتكئون معنا عبيدك. هب لهم مجازاتك المملوءة خلاصاً. عوِّضهم عن أتعابهم. لأن اسمك القدوس مبارك ومملوء مجداً، أيها الآب والابن والروح القدس، الآن وكل أوان وإلى دهر الدهور، آمين."
              }
            ]
          }
        ]
      }
    ]
  }
]

=== minaazer/LiturgicalText/CRFiles/agpeya/Agpeya - Guidance.json
[
  {
    "english_title": "Prayer for God’s Guidance",
    "coptic_title": null,
    "arabic_title": "صلاة لطلب مشورة الله قبل الشروع في عمل",
    "title": "Prayer for God’s Guidance",
    "tbodies": [
      {
        "rows": [
          {
            "row-class": "text",
            "cells": [
              {
                "english": "Lord, You are aware that I do not know what is good for me, and now that I am about to start (...), how can I know if it is right unless You guide me with Your grace? O Lord, I beseech Your guidance in this matter. Do not let me follow my tendencies, if it will cause me to be confused and fall. Keep me from slipping, help me, and let it be according to Your will. If You see it fit, grant me Your blessing to complete it. If not, remove this desire from my heart. You know all things, nothing is concealed from You, Lord I am Your servant, deal with me as You see fit, as I realize that I will have neither success nor peace unless I submit myself to Your will. Teach me to say in every occasion, “Let it be according to Your will, Lord, not according to my own.” For Yours is the kingdom, the power, the glory forever and ever. Amen.",
                "arabic": "إلهي، أنت تَعْلَمُ أني لا أعرف ما هو الصالح لنفسي. وها أنا قد شرعت في ..... فمن أين لي أن أعرف حسناً ما هو الصالح لي إن لم أسترشد نعمتك في ذلك؟ فأسألك يارب أن تدبرني في هذا الأمر. ولا تتركني ومشورة نفسي، ولا تدعني أجري وراء ميولي لئلا أتورط وأسقط، بل اعصم عبدك من الزلل، وكن متكَّلِي وعوني، ودبر الأمر بحسب إرادتك كما يوافق صلاحك. وإن حسُن لديك فليكن كما تريد، وهبني نعمتك لأتممه. وإن كان يضرُ فانزع مني يارب هذه الرغبة، لأنك عليمٌ بكل شىء، ولا يخفى عليك أمر. وها أنا عبدك، عاملني بما يوافقك، إذ لا نجاح تام، ولا سلام كامل، إلا بتسليم ذاتي تحت تدبير مشيئتك. وعلمني أن أقول فى كل شىء: يا أبتاه، ليس كمشيئتي بل كمشيئتك. لأن لك الملك والقوة والمجد من الآن وإلى الأبد، آمين."
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "english_title": "Prayer for God’s Accompaniment",
    "coptic_title": null,
    "arabic_title": null,
    "title": "Prayer for God’s Accompaniment",
    "tbodies": [
      {
        "rows": [
          {
            "row-class": "text",
            "cells": [
              {
                "english": "Grant me Your grace O Lord Jesus, the longsuffering, and be with me that I may dwell in You unto the end. Grant me that I may ask and wish always for what is pleasing to You. Let Your will be my will. Let my will follow always Your will and be in accord with it in a perfect way. Let both of us have one will, for I don’t want to desire anything except what You want and what You wish."
              }
            ]
          },
          {
            "row-class": "text",
            "cells": [
              {
                "english": "Grant me not to lust for the things of this world, that I may dwell in You in all things and hold above all things the desire to be as You would have me be and to do as You would have me do. You are the peace of my heart and the shelter of my life. You are the real peace and the only comfort and apart from You everything is hard and confusing. Therefore, in this peace which is in You, the Great Eternal Good, I am able to rest. For Yours is the kingdom, and the power and the glory forever."
              }
            ]
          }
        ]
      }
    ]
  }
]

=== minaazer/LiturgicalText/data/jsons/repeatedPrayers/psalmResponses.json
[
  {
    "english_title": "Psalm Response",
    "coptic_title": "",
    "arabic_title": "مرد المزمور",
    "tbodies": [
      {
        "rows": [
          {
            "row-class": "text",
            "seasons": [
              "Joyful 29th of the Month"
            ],
            "cells": [
              {
                "english": "Alleluia. Alleluia. Jesus Christ the Son of God was incarnate of the Virgin, was born of the Virgin in Bethlehem of Judea, rose from the dead on the third day. Alleluia. Alleluia.",
                "coptic": "Ⲁⲗ̅ ⲁ̅ⲗ̅ : Ⲓⲏ̅ⲥ̅ Ⲡⲭ̅ⲥ̅ ⲡ̀ϣⲏⲣⲓ ⲙ̀Ⲫϯ : ⲁϥϭⲓⲥⲁⲣⲝ ⲉ̀ⲃⲟⲗ ϧⲉⲛ ϯⲡⲁⲣⲑⲉⲛⲟⲥ ⲟⲩⲟϩ ⲁⲩⲙⲁⲥϥ ϧⲉⲛ Ⲃⲏⲉⲑⲗⲉⲉⲙ ⲕⲁⲧⲁ ⲛⲓⲥ̀ⲙⲏ ⲙ̀ⲡ̀ⲣⲟⲫⲏⲧⲓⲕⲟⲛ : ⲁϥⲧⲱⲛϥ ⲉ̀ⲃⲟⲗϧⲉⲛ ⲛⲏⲉⲑⲙⲱⲟⲩⲧ ϧⲉⲛ ⲡⲓⲉ̀ϩⲟⲟⲩ ⲙ̀ⲙⲁϩ ϣⲟⲙⲧ : ⲁ̅ⲗ̅ ⲁ̅ⲗ̅",
                "arabic": "هلليلويا هلليلويا، يسوع المسيح إبن الله تجسد من العذراء، وُلد من العذراء في بيت لحم اليهودية، وقام من بين الأموات في اليوم الثالث. هلليلويا هلليلويا."
              }
            ]
          },
          {
            "row-class": "text",
            "seasons": [
              "Feast of the Annunciation"
            ],
            "cells": [
              {
                "english": "Alleluia alleluia, Jesus Christ the Son of God, was incarnate from the Virgin.",
                "coptic": "Ⲁⲗⲗⲏⲗⲟⲩⲓⲁ ⲁ̅ⲗ̅: Ⲓⲏⲥⲟⲩⲥ Ⲡⲓⲭ̀ⲣⲓⲥⲧⲟⲥ Ⲡ̀ϣⲏⲣⲓ ⲙ̀Ⲫ̀ⲛⲟⲩϯ: ⲁϥϭⲓⲥⲁⲣⲝ ⲉ̀ⲃⲟⲗ ϧⲉⲛ Ϯⲡⲁⲣⲑⲉⲛⲟⲥ",
                "arabic": "هلليلويا هلليلويا، يسوع المسيح إبن الله، تجسد من العذراء،"
              }
            ]
          },
          {
            "row-class": "text",
            "seasons": [
              "Feast of the Nativity"
            ],
            "cells": [
              {
                "english": "Alleluia, Alleluia. Jesus Christ the Son of God was born of the Virgin in Bethlehem of Judea according to the prophetic sayings. Alleluia, Alleluia.",
                "coptic": "Ⲁⲗⲗⲏⲗⲟⲩⲓⲁ ⲁ̅ⲗ̅: Ⲓⲏ̅ⲥ̅ Ⲡⲭ̅ⲥ̅ ⲡ̀Ϣⲏⲣⲓ ⲙ̀Ⲫϯ ⲁⲥⲙⲁⲥϥ ⲛ̀ϫⲉ ϯⲠⲁⲣⲑⲉⲛⲟⲥ ϧⲉⲛ Ⲃⲏⲑⲗⲉⲉⲙ ⲛ̀ⲧⲉ ϯⲒⲟⲩⲇⲉⲁ̀ ⲕⲁⲧⲁ ⲛⲓⲥ̀ⲙⲏ ⲙ̀ⲡ̀ⲣⲟⲩⲫⲏⲧⲓⲕⲟⲛ. Ⲁⲗⲗⲏⲗⲟⲩⲓⲁ ⲁ̅ⲗ̅.",
                "arabic": "هلليلويا هلليلويا. يسوع المسيح ابن الله ولدته العذراء في بيت لحم اليهودية كالأصوات النبوي. هلليلويا هلليلويا."
              }
            ]
          },
          {
            "row-class": "text",
            "seasons": [
              "Feast of the Theophany"
            ],
            "cells": [
              {
                "english": "Alleluia alleluia, Jesus Christ the Son of God was baptized in the Jordan, alleluia alleluia.",
                "coptic": "Ⲁⲗⲗⲏⲗⲟⲩⲓⲁ ⲁ̅ⲗ̅: Ⲓⲏⲥⲟⲩⲥ Ⲡⲓⲭ̀ⲣⲓⲥⲧⲟⲥ Ⲡ̀ϣⲏⲣⲓ ⲙ̀Ⲫ̀ⲛⲟⲩϯ ⲁϥϭⲓⲱⲙⲥ ϧⲉⲛ Ⲡⲓⲓⲟⲣⲇⲁⲛⲏⲥ: ⲁⲗⲗⲏⲗⲟⲩⲓⲁ ⲁ̅ⲗ̅.",
                "arabic": "هلليلويا هلليلويا، يسوع المسيح إبن الله إعتمد في الأردن، هلليلويا هلليلويا."
              }
            ]
          },
          {
            "row-class": "text",
            "seasons": [
              "Hosanna Sunday"
            ],
            "cells": [
              {
                "english": "Alleluia alleluia. Jesus Christ the Son of God, entered into Jerusalem. Alleluia alleluia.",
                "coptic": "Ⲁⲗⲗⲏⲗⲟⲩⲓⲁ ⲁ̅ⲗ̅. Ⲓⲏⲥⲟⲩⲥ Ⲡⲓⲭ̀ⲣⲓⲥⲧⲟⲥ Ⲡ̀ϣⲏⲣⲓ ⲙ̀Ⲫ̀ⲛⲟⲩϯ: ⲁϥϣⲉ ⲉ̀ϧⲟⲩⲛ ⲉ̀Ⲓⲉⲣⲟⲩⲥⲁⲗⲏⲙ: ⲁ̅ⲗ̅ ⲁ̅ⲗ̅.",
                "arabic": "هلليلويا هلليلويا، يسوع المسيح إبن الله، دخل أورُشَليم، هلليلويا هلليلويا."
              }
            ]
          },
          {
            "row-class": "text",
            "seasons": [
              "Feast of the Resurrection",
              "Holy 50 Days - Before Ascension"
            ],
            "cells": [
              {
                "english": "Alleluia, alleluia. Jesus Christ the King of glory, has risen from the dead on the third day. Alleluia, alleluia.",
                "coptic": "Ⲁⲗⲗⲉⲗⲟⲩⲓⲁ ⲁ̅ⲗ̅. Ⲓⲏⲥⲟⲩⲥ Ⲡⲓⲭ̀ⲣⲓⲥⲧⲟⲥ Ⲡ̀ⲟⲩⲣⲟ ⲛ̀ⲧⲉ ⲡ̀ⲱ̀ⲟⲩ: ⲁϥⲧⲱⲛϥ ⲉ̀ⲃⲟⲗ ϧⲉⲛ ⲛⲏⲉⲑⲙⲱⲟⲩⲧ ϧⲉⲛ ⲡⲓⲉ̀ϩⲟⲟⲩ ⲙ̀ⲙⲁϩϣⲟⲙⲧ. Ⲁ̅ⲗ̅ ⲁ̅ⲗ̅.",
                "arabic": "هلليلويا هلليلويا. يسوع المسيح ملك المجد، قام من بين الأموات في اليوم الثالث. هلليلويا هلليلويا."
              }
            ]
          },
          {
            "row-class": "text",
            "seasons": [
              "Feast of the Ascension",
              "Holy 50 Days - After Ascension"
            ],
            "cells": [
              {
                "english": "Alleluia, alleluia. Christ has risen from the dead, ascended into the heavens, and is seated at the right hand of His Father. Alleluia, alleluia.",
                "coptic": "Ⲁⲗⲗⲏⲗⲟⲩⲓⲁ ⲁ̅ⲗ̅. Ⲡⲓⲭ̀ⲣⲓⲥⲧⲟⲥ ⲁϥⲧⲱⲛϥ ⲉ̀ⲃⲟⲗ ϧⲉⲛ ⲛⲏⲉⲑⲙⲱⲟⲩⲧ: ⲟⲩⲟϩ ⲁϥϣⲉⲛⲁϥ ⲉ̀ⲡ̀ϣⲱⲓ ⲉ̀ⲛⲓⲫⲏⲟⲩⲓ̀: ⲁϥϩⲉⲙⲥⲓ ⲥⲁⲟⲩⲓ̀ⲛⲁⲙ ⲙ̀Ⲡⲉϥⲓⲱⲧ. Ⲁ̅ⲗ̅ ⲁ̅ⲗ̅.",
                "arabic": "هلليلويا هلليلويا. المسيح قام من بين الأموات، وصعد إلى السموات، وجلس عن يمين أبيه. هلليلويا هلليلويا.<br/>"
              }
            ]
          },
          {
            "row-class": "text",
            "season": "Feast of Pentecost",
            "cells": [
              {
                "english": "Alleluia, alleluia. Christ has risen and ascended, and sent us the Paraclete, the Spirit of Truth. Alleluia, alleluia.",
                "coptic": "Ⲁⲗⲗⲏⲗⲟⲩⲓⲁ ⲁ̅ⲗ̅. Ⲡⲓⲭ̀ⲣⲓⲥⲧⲟⲥ ⲁϥⲧⲱⲛϥ ⲟⲩⲟϩ ⲁϥϣⲉⲛⲁϥ: ⲁϥⲟⲩⲱⲣⲡ ⲛⲁⲛ ⲙ̀Ⲡⲓⲡⲁⲣⲁⲕⲗⲏⲧⲟⲛ: Ⲡⲓⲡ̀ⲛⲉⲩⲙⲁ ⲛ̀ⲧⲉ ϯⲙⲉⲑⲙⲏⲓ. Ⲁ̅ⲗ̅ ⲁ̅ⲗ̅.",
                "arabic": "هلليلويا هلليلويا. المسيح قام ثم صعد، وأرسل لنا البارقليط، روح الحق. هلليلويا هلليلويا."
              }
            ]
          },
          {
            "row-class": "text",
            "seasons": [
              "Feast of the Circumcision"
            ],
            "cells": [
              {
                "english": "Alleluia Alleluia Jesus Christ, the Son of God, accepted unto Himself circumcision as mentioned in the Law. Alleluia Alleluia.<br/>",
                "coptic": "Ⲁⲗⲗⲏⲗⲟⲩⲓⲁ ⲁ̅ⲗ̅ Ⲓⲏ̅ⲥ̅ Ⲡⲭ̅ⲥ̅ ⲡ̀Ϣⲏⲣⲓ ⲙ̀Ⲫ̀ϯ: ⲁϥϣⲱⲟⲡ ⲉ̀ⲣⲟϥ ⲙ̀ⲡⲓⲥⲉⲃⲓ ⲕⲁⲧⲁ ⲡⲉⲧⲉⲥϣⲉ ϧⲉⲛ ⲡⲓⲛⲟⲙⲟⲥ. Ⲁ̅ⲗ̅ ⲁ̅ⲗ̅.<br/>",
                "arabic": "هلليلويا هلليلويا يسو ع المسيح ابن الله قبل إليه الختان كما ينبغي بالناموس. هلليلويا هلليلويا."
              }
            ]
          },
          {
            "row-class": "text",
            "seasons": [
              "Presentation of the Lord Christ in the Temple"
            ],
            "cells": [
              {
                "english": "Alleluia Alleluia Jesus Christ, the Son of God, entered into the temple. Alleluia Alleluia.",
                "coptic": "Ⲁⲗⲗⲏⲗⲟⲩⲓⲁ ⲁ̅ⲗ̅ Ⲓⲏ̅ⲥ̅ Ⲡⲭ̅ⲥ̅ ⲡ̀Ϣⲏⲣⲓ ⲙ̀Ⲫ̀ϯ: ⲁϥϣⲉ ⲉ̀ϧⲟⲩⲛ ⲉ̀ⲡⲓⲉⲣⲫⲉⲓ. Ⲁ̅ⲗ̅ ⲁ̅ⲗ̅.<br/>",
                "arabic": "هلليلويا هلليلويا يسوع المسيح ابن الله دخل الى الهيكل. هلليلويا هلليلويا."
              }
            ]
          },
          {
            "row-class": "text",
            "seasons": [
              "Entrance of the Lord Christ into the Land of Egypt"
            ],
            "cells": [
              {
                "english": "Alleluia (2), Jesus Christ the Son of God, came to the land of Egypt, alleluia (2). <br/>",
                "coptic": "Ⲁ̅ⲗ̅ ⲁ̅ⲗ̅: Ⲓⲏⲥⲟⲩⲥ Ⲡⲓⲭ̀ⲣⲓⲥⲧⲟⲥ Ⲡ̀ϣⲏⲣⲓ ⲙ̀Ⲫ̀ⲛⲟⲩϯ: ⲁϥⲓ̀ ⲉ̀ϧⲟⲩⲛ ⲉ̀ⲡ̀ⲕⲁϩⲓ ⲛ̀Ⲭⲏⲙⲓ: ⲁⲗ̅ ⲁ̅ⲗ̅.",
                "arabic": "هلليلويا (2)، يسوع المسيح إبن الله، دخل إلي أرض مصر، هلليلويا (2)."
              }
            ]
          },
          {
            "row-class": "text",
            "seasons": [
              "Feast of the Wedding at Cana of Galilee"
            ],
            "cells": [
              {
                "english": "Alleluia, alleluia, Jesus Christ, the Son of God, blessed the water and changed it into wine. Alleluia, alleluia.",
                "coptic": "Ⲁⲗⲗⲏⲗⲟⲩⲓⲁⲗ ⲁ̅ⲗ̅: Ⲓⲏ̅ⲥ̅ Ⲡⲭ̅ⲥ̅ Ⲡ̀ϣⲏⲣⲓ ⲙ̀Ⲫϯ: ⲁϥⲥ̀ⲙⲟⲩ ⲉ̀ⲛⲓⲙⲱⲟⲩ ⲁϥⲁⲓⲧⲟⲩ ⲛ̀ⲏⲣⲡ: ⲁ̅ⲗ̅ ⲁ̅ⲗ̅.",
                "arabic": "هلليلويا هلليلويا يسوع المسيح ابن الله بارك المياه فصيرها خمراً. هلليلويا هلليلويا.<br/>"
              }
            ]
          },
          {
            "row-class": "text",
            "seasons": [
              "Feast of the Transfiguration"
            ],
            "cells": [
              {
                "english": "Alleluia Alleluia, Jesus Christ the Son of God, was transfigured upon Mount Tabor, Alleluia Alleluia.",
                "coptic": "Ⲁⲗⲗⲏⲗⲟⲩⲓⲁ ⲁ̅ⲗ̅: Ⲓⲏ̅ⲥ̅ Ⲡⲭ̅ⲥ̅ ⲡ̀Ϣⲏⲣⲓ ⲙ̀Ⲫ̀ϯ: ⲁϥϣⲱⲃⲧ ⲉ̀ϫⲉⲛ ⲡⲓⲧⲱⲟⲩ ⲛ̀Ⲑⲁⲃⲱⲣ: ⲁⲗⲗⲏⲗⲟⲩⲓⲁ ⲁ̅ⲗ̅.",
                "arabic": "هلليلويا هلليلويا، يسوع المسيح إبن الله، تجلى على جبل تابور، هلليلويا هلليلويا."
              }
            ]
          },
          {
            "row-class": "text",
            "seasons": [
              "Nayrouz (Coptic New Year)"
            ],
            "cells": [
              {
                "english": "Alleluia alleluia, bless the crown of the year, with Your goodness O Lord, the rivers and the fountains, the plants and the fruits, alleluia alleluia.",
                "coptic": "Ⲁⲗⲗⲏⲗⲟⲩⲓⲁ ⲁ̅ⲗ̅: ⲥ̀ⲙⲟⲩ ⲉ̀ⲡⲓⲭ̀ⲗⲟⲙ ⲛ̀ⲧⲉ ϯⲣⲟⲙⲡⲓ: ϩⲓⲧⲉⲛ ⲧⲉⲕⲙⲉⲧⲭ̀ⲣⲏⲥⲧⲟⲥ Ⲡ̀ϭⲟⲓⲥ: ⲛⲓⲓⲁⲣⲱⲟⲩ ⲛⲉⲙ ⲛⲓⲙⲟⲩⲙⲓ: ⲛⲉⲙ ⲛⲓⲥⲓϯ ⲛⲉⲙ ⲛⲓⲕⲁⲣⲡⲟⲥ: ⲁⲗⲗⲏⲗⲟⲩⲓⲁ ⲁ̅ⲗ̅.",
                "arabic": "هلليلويا هلليلويا، بارك إكليل [هذه] السنة، بصلاحك يا رب، الأنهار والينابيع، والزروع والأثمار، هلليلويا هلليلويا."
              }
            ]
          },
          {
            "row-class": "text",
            "seasons": [
              "Feast of the Cross"
            ],
            "cells": [
              {
                "english": "Alleluia alleluia, Jesus Christ the Son of God, who was crucified on the Cross, destroy Satan under our feet, alleluia alleluia.",
                "coptic": "Ⲁⲗⲗⲏⲗⲟⲩⲓⲁ ⲁ̅ⲗ̅: Ⲓⲏⲥⲟⲩⲥ Ⲡⲓⲭ̀ⲣⲓⲥⲧⲟⲥ Ⲡ̀ϣⲏⲣⲓ ⲙ̀Ⲫ̀ⲛⲟⲩϯ: ⲫⲏⲉ̀ⲧⲁⲩⲁϣϥ ⲉ̀Ⲡⲓⲥ̀ⲧⲁⲩⲣⲟⲥ: ⲉⲕⲉ̀ϧⲟⲙϧⲉⲙ ⲙ̀Ⲡ̀ⲥⲁⲧⲁⲛⲁⲥ ⲥⲁⲡⲉⲥⲏⲧ ⲛ̀ⲛⲉⲛϭⲁⲗⲁⲩϫ: ⲁ̅ⲗ̅ ⲁ̅ⲗ̅.",
                "arabic": "هلليلويا هلليلويا، يسوع المسيح إبن الله، الذي صُلب على الصليب، إسحق الشيطان تحت أرجلنا، هلليلويا هلليلويا."
              }
            ]
          }
        ]
      }
    ]
  }
]

=== minaazer/LiturgicalText/CRFiles/agpeya/Agpeya - Confession.json
[
  {
    "english_title": "Prayer For Repentance",
    "coptic_title": null,
    "arabic_title": "صلاة للتوبة",
    "title": "Prayer For Repentance",
    "tbodies": [
      {
        "rows": [
          {
            "row-class": "text",
            "cells": [
              {
                "english": "My Lord, God and Savior Jesus Christ, treasure of mercy and spring of salvation, I come to You confessing my sins. I confess that with boldness I dared to defile Your holy sanctuary with my sins. Now I seek Your mercy and love, for Your mercies are boundless; You never turn back a sinner who comes to You. I confess that my mind is burdened with sin and that I have no strength left. Do not turn away from me; do not rebuke me in Your anger nor chasten me in Your displeasure. I am worn out; have compassion upon me, O Lord. Do not judge me according to Your justice, but according to Your mercy. Remember Your creation; do not put me on trial, because none of Your servants can justify their deeds. Dress me in a new attire that befits Your glory. Forgive my sins and I shall sing, “Blessed is he whose sins are forgiven.” When I confess my sins and reveal my iniquities, You cleanse me. Amen.",
                "arabic": "ربي وإلهي ومخلصي يسوع المسيح، كنز الرحمة ونبع الخلاص، آتي إليك مقراً بذنوبي. اعترف بأني بوقاحة تجاسرت ودنست هيكلك المقدس بخطاياي. والآن ألجأ إلى رحمتك وتحننك، لأن مراحمك لا تُحصى، وأنك لا ترد خاطئاً قد أقبل إليك. فها أنا آتي يارب معترفاً بأن آثامي قد طمت فوق رأسي كحمل ثقيل، و قد فارقتني قوتي. فلا تحجب يارب وجهك عني لئلا أرتاع. ولا توبخني بغضبك. ولا تودبني بغيظك. ولا تحاكمني بحسب استحقاقي. ارحمني يارب فإني ضعيف. اذكر يارب أني عمل يديك وارأف بي. لا تدخل فى المحاكمة مع عبدك، لأنه لن يتبرر قدامك أي حي. عد وألبسني حلة جديدة تليق بمجدك. اغفر لي وسامحني، لأترنم قائلاً: طوبى لمن غفر إثمه، وسترت خطيته. اعترف لك بخطيتى، ولا أكتم إثمي. قلت اعترف للرب بذنبي. وأنك رفعت آثام خطيتي. آمين."
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "english_title": "Prayer Before Confession",
    "coptic_title": null,
    "arabic_title": "صلاة قبل الإعتراف",
    "title": "Prayer Before Confession",
    "tbodies": [
      {
        "rows": [
          {
            "row-class": "text",
            "cells": [
              {
                "english": "O Holy Father, who desires the repentance of sinners, promising to accept them back; look now, O Lord, at my sinful soul for I have erred and lost my way in the valleys of transgressions for many years, and I am embittered and wretched for being removed from the fountain of my salvation. Yet, now I come to You, asking to be cleansed from all defilement and filth. Do not reject, but accept me. Look at me with compassion and deal with me mercifully and I will be cleansed and saved; do not neglect me lest I perish. Grant me grace that I may approach You with faith and hope, to confess my trespasses and my sins. Enlighten my heart that I may realize my sins, my mistakes and my straying. Grant me determination to forsake evil that I may be established in Your commandments and live for the glory of Your holy name. Amen.",
                "arabic": "أيها الآب القدوس، الذي يحب رجوع الخطاة. وقد وعدت أنك مستعد لقبولهم. انظر يارب الآن إلى نفس خاطئة قد ضلَّت وتاهت في أودية العصيان زماناً طويلاً. فيه تمررت وشعرت بشقاوتها، لبعدها عن ينبوع خلاصها. الآن تتقدم إليك، تطلب منك تطهيرها من الأدناس والأقذار التي توحلت فيها. اقبلها ولا ترفضها فإنك إن نظرت إليها بحنوك، وعاملتها برحمتك تنقت وخلصت، وإن أهملتها، بادَت وهلكت. امنحني يارب نعمة بها أتقوى على الدنو منك بإيمان وطيد ورجاء تام، لأعترف بذنوبي وأكره العودة إليها. وليبكتني روحك على آثامي. أنر قلبي لأرى كم أخطأت، وأسأت، وتركت، وأهملت. وامنحني عزماً على عدم الرجوع إلى الإثم لأثبت في حفظ وصاياك وأحيا لمجد اسمك القدوس، آمين."
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "english_title": "Prayer after Confession",
    "coptic_title": null,
    "arabic_title": "صلاة بعد الإعتراف",
    "title": "Prayer after Confession",
    "tbodies": [
      {
        "rows": [
          {
            "row-class": "text",
            "cells": [
              {
                "english": "I thank Your goodness, O Lover of Mankind because You did not desire that I perish, but have awakened me from my slumber and guided me to Your path. You saved me from the valley of destruction, and brought me to the safety of Your bosom. Fill me with hope and faith, for I have come to You as the sick one to his physician, and as the hungry to the Spring of living water, as the poor to the Source of riches, as the sinners to the Savior, and as the dead to the Fountain of Life; for You are my salvation, my healer, my life, my strength, my comfort, my joy, and my rest is in you. Help me, protect me, and teach me to put my will in Your hands, that I may live according to Your will. Remove my weakness that I may be firm and continue to be faithful to You until the end. Amen.",
                "arabic": "أشكر صلاحك أيها الآب محب البشر لأنك لم تشأ هلاكي. بل أيقظتني من غفلتي، وهديتني إلى طريقك. ورددتني من وادي الهلاك إلى حمى حصنك الأمين. فاملأني بالرجاء والإيمان. أقبلت إليك يا رب كالمريض إلى الطبيب الشافي، وكالمفتقر الجائع إلى الغذاء المشبع، وكالعطشان إلى ينابيع المياه الحية، وكالفقير إلى مصدر الغنى، وكالخاطىء إلى المخلص، وكالمائت إلى ينبوع الحياة. لأنك خلاصي، وطبيبي، وحياتي، وقوتي، وتعزيتي، وسعادتي، وفيك راحتي. فأعنّي واحفظني وسيِّج حولي، وعلِّمني أن أضع بين يديك كل إرادتي، لأسير حسب ما تشاء. أعن ضعفي كي أثبت وأدوم أميناً لك إلى النهاية، آمين."
              }
            ]
          }
        ]
      }
    ]
  }
]
